/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package gui;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Box;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import negocio.CadastroException;

/**
 *
 * @author 12205106
 */
public class JanelaInicial extends javax.swing.JFrame {

    /**
     * Creates new form JanelaInicial
     */
    public JanelaInicial() throws CadastroException {
        controlador = new CadastroControlador();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btUserDetail = new javax.swing.JButton();
        btAuctionDetail = new javax.swing.JButton();
        btCheckAuction = new javax.swing.JButton();
        btBidAuction = new javax.swing.JButton();
        btNewAuction = new javax.swing.JButton();
        btCancelAuction = new javax.swing.JButton();
        btNewUser = new javax.swing.JButton();
        cbUser = new javax.swing.JComboBox();
        cbAuction = new javax.swing.JComboBox();
        lbUser = new javax.swing.JLabel();
        lbAuction = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Leilões");

        btUserDetail.setText("Detalhes");
        btUserDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUserDetailActionPerformed(evt);
            }
        });

        btAuctionDetail.setText("Detalhes");

        btCheckAuction.setText("Verificar Lances");

        btBidAuction.setText("Novo Lance");

        btNewAuction.setText("Novo Leilão");

        btCancelAuction.setText("Cancelar Leilão");

        btNewUser.setText("Novo Usuário");
        btNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewUserActionPerformed(evt);
            }
        });

        cbUser.setModel(controlador.getListaPessoasModel());

        cbAuction.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbUser.setText("Usuário Logado:");

        lbAuction.setText("Leilão Selecionado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNewUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cbUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lbUser)
                                .addGap(25, 25, 25)
                                .addComponent(btUserDetail)))
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btNewAuction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btCancelAuction))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCheckAuction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btBidAuction))
                    .addComponent(cbAuction, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbAuction)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAuctionDetail)
                        .addGap(29, 29, 29)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btAuctionDetail)
                        .addComponent(lbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbAuction, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btUserDetail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbAuction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCheckAuction)
                    .addComponent(btBidAuction)
                    .addComponent(btNewUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNewAuction)
                    .addComponent(btCancelAuction))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("Gerenciador de Leilões");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewUserActionPerformed
        JTextField tfNome = new JTextField(5);
        JTextField tfEmail = new JTextField(5);
        JTextField tfDocumento = new JTextField(5);

        JPanel myPanel = new JPanel();
        myPanel.add(new JLabel("Nome:"));
        myPanel.add(tfNome);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("E-mail:"));
        myPanel.add(tfEmail);
        myPanel.add(Box.createHorizontalStrut(15)); // a spacer
        myPanel.add(new JLabel("Cpf/Cnpj:"));
        myPanel.add(tfDocumento);

        int result = JOptionPane.showConfirmDialog(null, myPanel,
           "Cadastro de novo usuário", JOptionPane.OK_CANCEL_OPTION);
        if ((result == JOptionPane.OK_OPTION)) {
            if(!tfNome.getText().equals("") && !tfEmail.getText().equals("") && !tfDocumento.getText().equals("")){
                try {
                    if (controlador.adicionarPessoa(tfNome.getText(), tfNome.getText(), tfEmail.getText())) {
                        JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso.");
                    }
                } catch (CadastroException ex) {
                    Logger.getLogger(JanelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            else{
                JOptionPane.showMessageDialog(this, "Não foi possível realizar o cadastro.");
            }
        }
    }//GEN-LAST:event_btNewUserActionPerformed

    private void btUserDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUserDetailActionPerformed
        JOptionPane.showMessageDialog(this, cbUser.getSelectedItem());
    }//GEN-LAST:event_btUserDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JanelaInicial().setVisible(true);
                } catch (CadastroException ex) {
                    Logger.getLogger(JanelaInicial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAuctionDetail;
    private javax.swing.JButton btBidAuction;
    private javax.swing.JButton btCancelAuction;
    private javax.swing.JButton btCheckAuction;
    private javax.swing.JButton btNewAuction;
    private javax.swing.JButton btNewUser;
    private javax.swing.JButton btUserDetail;
    private javax.swing.JComboBox cbAuction;
    private javax.swing.JComboBox cbUser;
    private javax.swing.JLabel lbAuction;
    private javax.swing.JLabel lbUser;
    // End of variables declaration//GEN-END:variables
    private CadastroControlador controlador;
}
